options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/beam-pipelines:latest', '.']

# 2️⃣ Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/beam-pipelines:latest']
 
# 3️⃣ Build Flex Template for ingest_api1.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud dataflow flex-template build gs://$PROJECT_ID-templates/ingest-api1.json \
        --image-gcr-path=gcr.io/$PROJECT_ID/beam-pipelines:latest \
        --sdk-language=PYTHON \
        --metadata-file=templates_metadata/template_api1.json \
        --py-path=src/Pipelines/ingest-api1.py \
        --flex-template-base-image=PYTHON3 \
        --env FLEX_TEMPLATE_PYTHON_PY_FILE=src/Pipelines/ingest-api1.py \
        --staging-location=gs://$PROJECT_ID-templates/staging \
        --temp-location=gs://$PROJECT_ID-templates/temp

# 4️⃣ Build Flex Template for ingest_api2.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Checking if pipeline file exists:"
      ls -l src/Pipelines/
      gcloud dataflow flex-template build gs://$PROJECT_ID-templates/ingest-api2.json \
        --image-gcr-path=gcr.io/$PROJECT_ID/beam-pipelines:latest \
        --sdk-language=PYTHON \
        --metadata-file=templates_metadata/template_api2.json \
        --flex-template-base-image=PYTHON3 \
        --staging-location=gs://$PROJECT_ID-templates/staging \
        --py-path=src/Pipelines/ingest-api2.py \
        --env FLEX_TEMPLATE_PYTHON_PY_FILE=/template/src/Pipelines/ingest-api2.py \
        --temp-location=gs://$PROJECT_ID-templates/temp

 
# 5️⃣ Upload DAGs and SQL to Cloud Composer DAGs bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Upload DAG Python files
      gsutil cp dags/*.py gs://$_COMPOSER_BUCKET/dags/
      
      # Upload SQL folder
      gsutil -m cp -r sql gs://$_COMPOSER_BUCKET/dags/

images:
- 'gcr.io/$PROJECT_ID/beam-pipelines:latest'
