options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/beam-pipelines:latest', '.']

# 2️⃣ Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/beam-pipelines:latest']

# 3️⃣ Build Flex Template for ingest_api1.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud dataflow flex-template build gs://$PROJECT_ID-templates/ingest_api1.json \
        --image gcr.io/$PROJECT_ID/beam-pipelines:latest \
        --sdk-language PYTHON \
        --metadata-file templates_metadata/template_api1.json \
        --env FLEX_TEMPLATE_PYTHON_PY_FILE=src/Pipelines/ingest_api1.py

# 4️⃣ Build Flex Template for ingest_api2.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud dataflow flex-template build gs://$PROJECT_ID-templates/ingest_api2.json \
        --image gcr.io/$PROJECT_ID/beam-pipelines:latest \
        --sdk-language PYTHON \
        --metadata-file templates_metadata/template_api2.json \
        --env FLEX_TEMPLATE_PYTHON_PY_FILE=src/Pipelines/ingest_api2.py

images:
- 'gcr.io/$PROJECT_ID/beam-pipelines:latest'
