# Cloud Build config for building Docker image and deploying as Cloud Run Job
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
# Step 1: Build Docker image from Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

# Step 2: Push Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

# Step 3: Create or update Cloud Run Job
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'jobs', 'replace', 'my-batch-job',
      '--image', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA',
      '--region', 'us-central1'
    ]

# Step 4 (optional): Execute the job immediately
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'jobs', 'execute', 'my-batch-job',
      '--region', 'us-central1'
    ]


